# 사이트(소스) 설정 예시
# 실제 사이트 적용 시 각 셀렉터는 해당 사이트 구조에 맞게 수정하세요.
# 'method: rss'는 가장 쉽고 안정적입니다.
# 'method: html'은 item_selector, title_selector, link_selector 등을 지정해야 합니다.
sources:
  - name: K-Logistics RSS
    base_url: https://www.klnews.co.kr
    method: rss
    rss_url: https://www.klnews.co.kr/rss/allArticle.xml

  - name: 물류신문(HTML)
    base_url: https://www.klnews.co.kr
    method: html
    list_url: https://www.klnews.co.kr/news/articleList.html
    # 아래 셀렉터는 예시입니다. (브라우저 개발자도구로 실제 클래스 확인 후 수정)
    item_selector: ".list-type .list-item"       # 목록에서 각 카드 선택자
    title_selector: ".tit"                      # 카드 내부 제목 선택자
    link_selector: "a"                          # 제목/링크 요소 선택자
    view_selector: ".hit"                       # (가능하면) 조회수 CSS 선택자
    detail:
      content_selector: "div.article-body p"
      date_selector: "div.info time"
      date_attr: "datetime"

